### ISSUE TITLE
Is YouTube and Vimeo supported then?

### ISSUE THREAD

**Issue by procmail** [rishabhp/bideo.js#13]
With reference to https://github.com/rishabhp/bideo.js/issues/1, it says that most features there have been added.

But I briefly skimmed through the source code and couldn't find any reference to YouTube and Vimeo.

So are these supported?

**Comment by rishabhp** [comment]
Basically iirc, I'd realized that youtube (and others too I guess) have their own APIs/parameters and  there are quirks that are hard to control because some features don't exist. Hence it probably makes sense to use them separately by finely controlling the parameters you specify.

Here's their reference - https://developers.google.com/youtube/player_parameters
